services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6
    container_name: nginx-proxy
    labels:
      - com.github.nginx-proxy.nginx=true    # <— optional but recommended
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    restart: unless-stopped

  acme-companion:
    image: nginxproxy/acme-companion:2.5
    container_name: acme-companion
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
      DEFAULT_EMAIL: "admin@zoekalle.com"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    restart: unless-stopped

  api:
    environment:
      VIRTUAL_HOST: "www.zoekalle.com"
      LETSENCRYPT_HOST: "www.zoekalle.com"
      LETSENCRYPT_EMAIL: "admin@zoekalle.com"

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html: